import Head from 'next/head'
import HeroSection from '../components/home/HeroSection'
import MobileHeroCategory from '../components/home/mobile/MobileHeroCategory'
import ProductSection from '../components/home/ProductSection'
import { AllProducts, GetAdminEightProducts } from '../adapters/product'
import MobileProductSection from '../components/home/mobile/MobileProductSection'
import MobileHeroSlider from '../components/home/mobile/MobileHeroSlider'
import CategorySection from '../components/category/CategorySection'
import { getAllCategories, getAllHomePageCategories } from '../adapters/category'
import { TryCatch } from "../utils/TryCatchHandle";
import { useEffect, useState } from 'react'
import { getBanners } from '../adapters/banner'
import { getCampaigns } from '../adapters/campaign'

export default function Home({ products, allCategories, banners, campaigns }) {
  const [categories, setCategories] = useState(null);
  const [adminProducts, setAdminProducts] = useState(null)
  const fetcher = async () => {
    TryCatch(async () => {
      const response = await getAllHomePageCategories();
      setCategories(response?.data)
    })
  }

  useEffect(() => {
    fetcher()
  }, [])

  return (
    <div>
      <Head>
        <title>Esyclick...</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <div className='hidden sm:block'>
        <HeroSection categories={allCategories} banners={banners} campaigns={campaigns} />
        <ProductSection products={products} title="Hot Items" />
        <CategorySection categories={categories} title="All Category List" />
      </div>

      {/* only visible on mobile device */}
      <div className='sm:hidden'>
        <div className='mb-8'>
          <MobileHeroSlider banners={banners} />
          <MobileHeroCategory />
          <MobileProductSection products={products} title="Hot Items" />
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps() {
  try {
    const response = await AllProducts()
    const categories = await getAllCategories();
    const banners = await getBanners();
    const campaigns = await getCampaigns();
    return {
      props: {
        products: response?.data,
        allCategories: categories?.data,
        banners: banners?.data,
        campaigns: campaigns.data
      },
    }
  } catch (error) {
    return {
      props: {
        esyclick: 'EsyClick'
      },
    }
  }
}

